ircService:
  databaseUri: "mongodb://localhost:27017/matrix-appservice-irc"
  servers:
    irc.example.com:
      nick: "appservicebot"
      expose:
        channels: true
        privateMessages: true
      userPrefix: "@irc_"
      rooms:
        aliasPrefix: "#irc_"
        mappings:
          "#thepub": ["!kieouiJuedJoxtVdaG:localhost"]
  logging:
    level: "debug"
    logfile: "debug.log"
    errfile: "errors.log"
    toConsole: true
    maxFileSizeBytes: 134217728 # 128 MB
    maxFiles: 5

appService:
  hs: "http://localhost:8008"
  hsDomain: "localhost"
  token: "1234567890"
  as: "http://localhost:3500"
  port: 3500
