ircService:
  databaseUri: "nedb://data"
  servers:
    irc.example.com:
      nick: "appservicebot"
      # not yet implemented
      auth:
        type: "cas"
        url: "https://cas.example.com"
        lifetimeSecs: 7776000  # 90 days
      # ===================
      expose:
        channels: true
        privateMessages: true
      userPrefix: "@irc_"
      nickPrefix: "M-"
      rooms:
        aliasPrefix: "#irc_"
        mappings:
          "#thepub": ["!kieouiJuedJoxtVdaG:localhost"]
  auth:
    redirectBase: "http://my.app.service.com/auth"  # will have /$TOKEN suffixed
    port: 4555
  logging:
    level: "debug"
    logfile: "debug.log"
    errfile: "errors.log"
    toConsole: true
    maxFileSizeBytes: 134217728 # 128 MB
    maxFiles: 5

appService:
  hs: "http://localhost:8008"
  hsDomain: "localhost"
  token: "1234567890"
  as: "http://localhost:3500"
  port: 3500
